# Generated by Django 3.0.7 on 2021-01-07 12:54

import apps.word_cloud.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, default=None, help_text='Keyword that was sent in request', max_length=255, null=True)),
                ('related_words', models.TextField(blank=True, default=None, help_text='Words related to keyword', null=True)),
                ('image', models.ImageField(blank=True, help_text='The image that was created based on keyword and related words', max_length=1024, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static', location='/async_service/static'), upload_to=apps.word_cloud.models.image_upload_to)),
            ],
        ),
    ]
